//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toenda.MovieMaticInterface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toenda.MovieMaticInterface.SqlResources", typeof(SqlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *, 
        ///	(
        ///		SELECT COUNT(p.pkid) 
        ///		FROM tbl_movies_to_persons AS mp
        ///		LEFT JOIN tbl_persons AS p
        ///		ON mp.person_pkid = p.pkid
        ///		WHERE m.pkid = mp.movie_pkid
        ///	) AS personCount
        ///INTO #tmp_personCount
        ///FROM tbl_movies AS m;
        ///
        ///SELECT *
        ///FROM #tmp_personCount
        ///WHERE personCount = 0
        ///ORDER BY number ASC, sort_value ASC
        ///
        ///DROP TABLE #tmp_personCount.
        /// </summary>
        internal static string GetEmptyPersonOnMovieList {
            get {
                return ResourceManager.GetString("GetEmptyPersonOnMovieList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY {0} {1}.
        /// </summary>
        internal static string GetMovieList_SortOrder {
            get {
                return ResourceManager.GetString("GetMovieList_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY {0} {1}.
        /// </summary>
        internal static string GetPersonList_SortOrder {
            get {
                return ResourceManager.GetString("GetPersonList_SortOrder", resourceCulture);
            }
        }
    }
}
